# Standardize and clean player names
clean_names = function(player, year) {
  
  player = str_replace(player, "  ", " ")
  player = str_replace(player, ",", "")
  
  
  player = dplyr::case_when(
    ## 2023 Draft ##
    player %in% c("Callum Ritchie", "Cal Ritchie") ~ "Calum Ritchie",
    player %in% c("Cam Allen") ~ "Cameron Allen",
    player %in% c("Colby Barrow") ~ "Colby Barlow",
    player %in% c("Gabriel Perreault") ~ "Gabe Perreault",
    player %in% c("Gavin McCarty") ~ "Gavin McCarthy",
    
    ## 2022 Draft ##
    player %in% c("Adam Zinka") ~ "Adam Zlnka",
    player %in% c("Aiden Castle") ~ "Aidan Castle",
    player %in% c("Aleksanteri Kaskiimaki") ~ "Aleksanteri Kaskimaki",
    player %in% c("Alexandr Muromtsev") ~ "Alexander Muromtsev",
    player %in% c("Alexander Ponomarev", "Alexandr Ponomarev") ~ "Alexander Ponomaryov",
    player %in% c("Artem Barabosha") ~ "Artyom Barabosha",
    player %in% c("Ben King") ~ "Benjamin King",
    player %in% c("Benjamin West") ~ "Ben West",
    player %in% c("Benjamin Zloty") ~ "Ben Zloty",
    player %in% c("Braden Lisowsky", "Brendan Lisowsky") ~ "Brandon Lisowsky",
    player %in% c("Brayden Schuurmann") ~ "Brayden Schuurman",
    stringr::str_replace(tolower(player), " ", "") == "brycemcconnell-barker" ~ "Bryce McConnell-Barker",
    player %in% c("Cam Lund") ~ "Cameron Lund",
    player %in% c("Cameron ONeil") ~ "Cameron O'Neill",
    player %in% c("Charles Leddy") ~ "Charlie Leddy",
    player %in% c("Chris Romaine") ~ "Christopher Romaine",
    player %in% c("Cruz Lucias") ~ "Cruz Lucius",
    player %in% c("Damion Gardner") ~ "Daimon Gardner",
    player %in% c("Danil Grigoryev") & year %in% 2022 ~ "Daniil Grigoryev",
    player %in% c("Daniil O. Ivanov") ~ "Daniil Ivanov",
    grepl("Zhilkin", player) & year %in% 2022 ~ "Danny Zhilkin",
    player %in% c("Dom DiVincentiis") ~ "Domenic DiVincentiis",
    player %in% c("Duncan Ramsey") ~ "Duncan Ramsay",
    player %in% c("Elias Salmonsson") ~ "Elias Salomonsson",
    grepl("Frank Nazar", player) & year %in% 2022 ~ "Frank Nazar",
    player %in% c('Isaac "Ike" Howard', "Issac Howard") ~ "Isaac Howard",
    player %in% c("Isiah George") ~ "Isaiah George",
    player %in% c("Ivan Miroschnichenko") ~ "Ivan Miroshnichenko",
    player %in% c("Jack Weir") ~ "Jace Weir",
    player %in% c("Jack D Hughes") ~ "Jack Hughes",
    player %in% c("Janni Nyman") ~ "Jani Nyman",
    grepl("Snuggerud", player) & year == 2022 ~ "Jimmy Snuggerud",
    player %in% c("Jonathan Lakkerimaki") ~ "Jonathan Lekkerimaki",
    player %in% c("Jorian Donavan") ~ "Jorian Donovan",
    player %in% c("Joshua Davies") ~ "Josh Davies",
    player %in% c("Joshua Filmon") ~ "Josh Filmon",
    player %in% c("Juraj Slavkovsky") ~ "Juraj Slafkovsky",
    player %in% c("Kaiden Mbereko") ~ "Kaidan Mbereko",
    player %in% c("Karlis Meszargs") ~ "Karlis Mezsargs",
    player %in% c("Kas Sobieski") ~ "Kazimier Sobieski",
    player %in% c("Kirill Kudryatev") ~ "Kirill Kudryavtsev",
    player %in% c("Liam Amsby") ~ "Liam Arnsby",
    grepl("Lian Bi", player) & year == 2022 ~ "Lian Bichsel",
    grepl("Liam Bichsel", player) ~ "Lian Bichsel",
    player %in% c("Luca Dipasquo") ~ "Luca Di Pasquo",
    player %in% c("Lucas Gustavsson") & year %in% c(2021, 2022) ~ "Lukas Gustavsson",
    player %in% c("Maddox Flemming") ~ "Maddox Fleming",
    player %in% c("Marcus Vidicek") ~ "Markus Vidicek",
    player %in% c("Matthew Ward") & year %in% 2022 ~ "Mathew Ward",
    player %in% c("Maverick Lamoreux", "Maveric Lamoureaux") ~ "Maveric Lamoureux",
    player %in% c("Maxim Arefeyev") ~ "Maxim Arefyev",
    player %in% c("Max Namestnikov") ~ "Maxim Namestnikov",
    player %in% c("Michael Milne") ~ "Mikey Milne",
    player %in% c("Miko Mattikaa", "Mikko Matikka") ~ "Miko Matikka",
    player %in% c("Nicholas Mouldenhauer", "Nicholas Moldenhauser", "Nick Moldenhauer", "Nick Moldenhauser") ~ "Nicholas Moldenhauer",
    player %in% c("Nicholas Pierre") ~ "Nick Pierre",
    player %in% c("Nikita Grebenkin") ~ "Nikita Grebyonkin",
    player %in% c("Pavel Mintyyukov") ~ "Pavel Mintyukov",
    player %in% c("Reiger Lorenz", "Reiger Lorentz") ~ "Rieger Lorenz",
    grepl("Rutger Mc", player) & year %in% 2022 ~ "Rutger McGroarty",
    player %in% c("Sam Harris") ~ "Samuel Harris",
    player %in% c("Sam Mayer") ~ "Samuel Mayer",
    player %in% c("Samuel Rinzel") ~ "Sam Rinzel",
    player %in% c("Sam Savoie") ~ "Samuel Savoie",
    player %in% c("Sam Smajda") ~ "Samuel Smajda",
    player %in% c("Stefan Milsevic") ~ "Stefan Milosevic",
    player %in% c("Tomas Viktor Hebek") ~ "Tomas Hebek",
    player %in% c("Vladimir Sychov") ~ "Vladimir Sychyov",
    player %in% c("Vladimir Sapunov") ~ "Vladislav Sapunov",
    player %in% c("Yann Vogeli") ~ "Yann Voegeli",
    player %in% c("Zachary Bookman") ~ "Zach Bookman",
    
    ## 2021 Draft ##
    player %in% c("Aleksei Heimosalmi") ~ "Aleksi Heimosalmi",
    player %in% c("Aleksei Kolosov") ~ "Alexei Kolosov",
    player %in% c("Aleksandr Kisakov") ~ "Alexander Kisakov",
    player %in% c("Aleksandr Komarov") ~ "Alexander Komarov",
    player %in% c("Arsenii Sergeev", "Arseni Sergeev", "Arsenii Sergeyev", "Arseny Sergeyev", "Arseny Sergeev") ~ "Arseni Sergeyev",
    player %in% c("Artyon Martino") ~ "Ayrton Martino",
    player %in% c("Ben Roger") ~ "Benjamin Roger",
    player %in% c("Bennett Rossmy", "Benett Rossmy", "Bennet Robmy", "Bennett Robmy") ~ "Bennet Rossmy",
    player %in% c("Bogdan Krokhalev") ~ "Bogdan Krokhalyov",
    player %in% c("Brennan Othman") ~ "Brennan Othmann",
    player %in% c("Caedan Baniker") ~ "Caedan Bankier",
    player %in% c("Cam MacDonald", "Cam Macdonald") ~ "Cameron MacDonald",
    player %in% c("Cole Silinger") ~ "Cole Sillinger",
    player %in% c("Connor William Korte", "William Korte") ~ "Connor Korte",
    player %in% c("Daniil Grigoryev") & year %in% 2021 ~ "Danil Grigoryev",
    player %in% c("Dmitri Katevelski", "Dmitri Katevelsky", "Dmitry Katelevsky", "Dmitrii Katelevskii") ~ "Dmitri Katelevsky",
    player %in% c("Fedor Svechkov") ~ "Fyodor Svechkov",
    player %in% c("Gabe Klassen") ~ "Gabriel Klassen",
    player %in% c("Hakon Hanelt") ~ "Haakon Hanelt",
    player %in% c("Hugo Gabrielson") ~ "Hugo Gabrielsson",
    player %in% c("Ilya Kvocho") ~ "Ilya Kvochko",
    player %in% c("Jacob Martin") & year %in% 2021 ~ "Jake Martin",
    player %in% c("Jakub Brabanec") ~ "Jakub Brabenec",
    player %in% c("Jan Munzenberger", "Luca Munzenberger") ~ "Jan-Luca Munzenberger",
    player %in% c("Janis-Jerome Moser", "Janis Jerome Moser", "J.J. Moser", "JJ Moser", "Janis Moser", "Jerome Moser") ~ "Janis Moser",
    player %in% c("Joey Pierce", "Joe Pierce") ~ "Joseph Pierce",
    player %in% c("Joshua Lopina") ~ "Josh Lopina",
    player %in% c("Matthew Samoskevich", 'Matthew "Mackie" Samoskevich') ~ "Mackie Samoskevich",
    player %in% c("Matty Beniers") ~ "Matthew Beniers",
    player %in% c("Matt Coronato") ~ "Matthew Coronato",
    player %in% c("Maksim Motorygin") ~ "Maxim Motorygin",
    player %in% c("Nikita Grebenkin") ~ "Nikita Grebyonkin",
    player %in% c("Nikita Skoropod") ~ "Nikita Skoropad",
    player %in% c("Nick Heigl", "Nik Heigl", "Nic Heigl", "Nicolaus Heigl", "Nikolas Heigl", "Nicholas Heigl", "Nicolas Heigl") ~ "Nikolaus Heigl",
    player %in% c("Oleksiy Myklukha") ~ "Oleksii Myklukha",
    player %in% c("Olen Zellwegger") ~ "Olen Zellweger",
    player %in% c("Oliver Nadeau") ~ "Olivier Nadeau",
    player %in% c("Red Savage") ~ "Redmond Savage",
    grepl("Van Calster", player) & year %in% 2021 ~ str_replace(player, "Van Cal", "van Cal"),
    player %in% c("Ryan Winteron") ~ "Ryan Winterton",
    player %in% c("Samuel Rinzel") ~ "Sam Rinzel",
    player %in% c("Sasha Pustujov") ~ "Sasha Pastujov",
    grepl("Teleguine", player) & year == 2021 ~ "Sasha Teleguine",
    player %in% c("Sean Tschiegerl") ~ "Sean Tschigerl",
    player %in% c("Sebastien Cossa") ~ "Sebastian Cossa",
    player %in% c("Semyon Vyazovoy") ~ "Semyon Vyazovoi",
    player %in% c("Stiven Sardaryan") ~ "Stiven Sardarian",
    player %in% c("Stuart Roofs") ~ "Stuart Rolofs",
    player %in% c("Jozef Viliam Kmec", "Jozef Kmec", "J.V. Kmec", "JV Kmec", "Villiam Kmec") ~ "Viliam Kmec",
    player %in% c("Vinny Iorio") ~ "Vincent Iorio",
    player %in% c("Vladislav Lukasevich") ~ "Vladislav Lukashevich",
    player %in% c("William Strombren") ~ "William Stromgren",
    player %in% c("William Von Barnekow") ~ "William von Barnekow",
    grepl("Lofberg", player) & year %in% 2021 ~ "William von Barnekow",
    player %in% c("Zach Bolduc") ~ "Zachary Bolduc",
    player %in% c("Zachary Dean") ~ "Zach Dean",
    player %in% c("Zach Lessard") ~ "Zachary Lessard",
    player %in% c("Zach L'Heureux", "Zach L'Heureaux", "Zachary L'Heureaux", "Zach L'heureux", "Zach L'heureaux", "Zachary L'heureaux") ~ "Zachary L'Heureux",
    player %in% c("Zachary Urdahl") ~ "Zach Urdahl",
    
    ## 2020 Draft ##
    player %in% c("Alexandros Gaffney") ~ "Alex Gaffney",
    player %in% c("Anton Johannsesson") ~ "Anton Johannesson",
    grepl("Schlaine", player) & year == 2020 ~ "Artyom Shlaine",
    player %in% c("Bodgdan Trineyev") ~ "Bogdan Trineyev",
    player %in% c("Braeden Schneider") ~ "Braden Schneider",
    player %in% c("Bryan Thompson") & year ==2020 ~ "Bryan Thomson",
    player %in% c("Calle Olsen", "Calle Spaberg", "Calle Spaberg Olsen") ~ "Calle Spaberg-Olsen",
    player %in% c("Charlie Desrochers", "Charlie DesRoches") ~ "Charlie Desroches",
    player %in% c("Colton Kammerer", "Colton Kammerrer") ~ "Colton Kamerrer",
    player %in% c("Danil Gushchin", "Daniil Guschin", "Danil Guschin") ~ "Daniil Gushchin",
    player %in% c("Danila Pavilko") ~ "Danila Palivko",
    player %in% c("Dmitry Zlodeev", "Dmitri Zlodeev") ~ "Dmitri Zlodeyev",
    player %in% c("Drew Comesso") ~ "Drew Commesso",
    player %in% c("Emil Viro") ~ "Eemil Viro",
    player %in% c("Eliot Ekmark", "Elliott Ekmark") ~ "Elliot Ekmark",
    player %in% c("Donald Kempf") ~ "Hank Kempf",
    player %in% c("Ilya Usau") ~ "Ilya Usov",
    player %in% c("Ivan Didkovskiy", "Ivan Didkovkiy") ~ "Ivan Didkovsky",
    player %in% c("Jake Murray") ~ "Jacob Murray",
    player %in% c("Jacob Ratzlaff") ~ "Jake Ratzlaff",
    player %in% c("Jake Truscott") ~ "Jacob Truscott",
    player %in% c("Jeremie Biakabatuka") ~ "Jeremie Biakabutuka",
    grepl("Peterka", player) & year == 2020 ~ "John-Jason Peterka",
    player %in% c("John Peterka", "J.J. Peterka", "JJ Peterka", "John Jason Peterka") ~ "John-Jason Peterka",
    player %in% c("Johnston Meiers", "Johnny Meiers", "Jonston Meiers", "John Meiers") ~ "Jonny Meiers",
    player %in% c("Joshua Lawrence") ~ "Josh Lawrence",
    player %in% c("Kevin Brassard") ~ "Kevyn Brassard",
    player %in% c("Kiril Steklov", "Kirll Steklov") ~ "Kirill Steklov",
    player %in% c("Landon Koisor") ~ "Landon Kosior",
    player %in% c("Lukas Raymond") ~ "Lucas Raymond",
    player %in% c("Matej Kaslic") ~ "Matej Kaslik",
    player %in% c("Maxim Berezkin", "Maksim Berezkin", "Maksim Beryozkin") ~ "Maxim Beryozkin",
    player %in% c("Max Bykov", "Maksim Bykov") ~ "Maxim Bykov",
    player %in% c("Max Groshev", "Maksim Groshev") ~ "Maxim Groshev",
    player %in% c("Michael Gut") ~ "Michal Gut",
    player %in% c("Michal Krutil") ~ "Michael Krutil",
    player %in% c("Mitch Miller") ~ "Mitchell Miller",
    player %in% c("Nicolas Capone", "Nicholas Capone") ~ "Nick Capone",
    player %in% c("Nicolas Daws") ~ "Nico Daws",
    player %in% c("Ole Bjorgvik Holm", "Ole Holm", "Ole Bjorgvik-Holm", "Julian Bjorkvik Holm", "Julian Bjorgvik-Holm", "Ole Julian Bjorgvik Holm") ~ "Ole Julian Bjorgvik-Holm",
    player %in% c("Ozzy Weisblatt") ~ "Ozzy Wiesblatt",
    player %in% c("Pierre-Olivier Roy") & year == 2020 ~ "Pier-Olivier Roy",
    player %in% c("Robert Fromm-Delorme") ~ "Robbie Fromm-Delorme",
    player %in% c("Ruban Rafken", "Ruben Rafken", "Ruban Rafkin") ~ "Ruben Rafkin",
    player %in% c("Savely Kuvardin") ~ "Saveli Kuvardin",
    player %in% c("Simon Anderson") & year == 2020 ~ "Simon Andersson",
    player %in% c("Theo Niederbach") ~ "Theodor Niederbach",
    player %in% c("Tim Stuetzle", "Timothy Stutzle", "Timothy Stuetzle") ~ "Tim Stutzle",
    player %in% c("Tristen Robbins", "Tristan Robins") ~ "Tristen Robins",
    player %in% c("Ty Foerster") ~ "Tyson Foerster",
    player %in% c("Ty Tullio", "Tyler Tulio") ~ "Tyler Tullio",
    player %in% c("Vasili Ponomarev", "Vasiliy Ponomarev", "Vasily Ponomarev") ~ "Vasili Ponomaryov",
    player %in% c("Vittorio Mancini") ~ "Victor Mancini",
    player %in% c("Will Cuyle", "William Cuylle", "William Cuyle", "Will Cullye") ~ "Will Cuylle",
    player %in% c("Willam Wallinder", "Will Wallinder") ~ "William Wallinder",
    player %in% c("Yarolslav Askarov") ~ "Yaroslav Askarov",
    player %in% c("Yegeni Oksentyuk") ~ "Evgeni Oksentyuk",
    player %in% c("Zach Bouthillier") ~ "Zachary Bouthillier",
    player %in% c("Zachary Papoutsakis") ~ "Zachary Paputsakis",
    player %in% c("Zach Plucinski") ~ "Zachary Plucinski",
    player %in% c("Zach Roy") ~ "Zachary Roy",
    player %in% c("Zach Uens") ~ "Zachary Uens",
    
    ## 2019 Draft ##
    player %in% c("Aidan McDonogh", "Aidan McDonaugh", "Aidan Mcdonough") ~ "Aidan McDonough",
    grepl("Albin Grewe", player) ~ "Albin Grewe",
    player %in% c("Alvin Grewe") ~ "Albin Grewe",
    player %in% c("Alex Campbell") ~ "Alexander Campbell",
    player %in% c("Alexandr Daryin", "Alexandr Darin", "Alexander Darin") ~ "Alexander Daryin",
    player %in% c("Andrei Pribylskiy") ~ "Andrei Pribylsky",
    player %in% c("Artemi Kniazev") ~ "Artemi Knyazev",
    player %in% c("Arthur Kaliev", "Artur Kaliyev", "Artur Kaliev") ~ "Arthur Kaliyev",
    player %in% c("Ben Brinkman") ~ "Benjamin Brinkman",
    player %in% c("Cam York") ~ "Cameron York",
    player %in% c("Dom Fensore", "Dominick Fensore", "Dominik Fensore") ~ "Domenick Fensore",
    player %in% c("Danil Misyul") ~ "Daniil Misyul",
    player %in% c("Emil Lilleberg") ~ "Emil Martinsen-Lilleberg",
    player %in% c("Graeme Clark", "Graham Clarke") ~ "Graeme Clarke",
    player %in% c("Henry Rybinski") ~ "Henrik Rybinski",
    player %in% c("Ilvari Rasanen") ~ "Iivari Rasanen",
    player %in% c("Ilya Altybarmakian") ~ "Ilya Altybarmakyan",
    player %in% c("Jonathan Williams") & year == 2019 ~ "Jack Williams",
    player %in% c("Jacob Perrault") ~ "Jacob Perreault",
    player %in% c("Joseph Carroll") ~ "Joe Carroll",
    player %in% c("John Beecher") ~ "Johnny Beecher",
    player %in% c("Joshua Nodler") ~ "Josh Nodler",
    player %in% c("Lucas Feulk") ~ "Lucas Feuk",
    player %in% c("Luke Burzan") ~ "Luka Burzan",
    player %in% c("Martin Has") ~ "Martin Hugo Has",
    player %in% c("Mattias Macceli", "Mattias Maceli", "Mattias Macelli", "Matias Macceli", "Matias Maceli", "Mattias Maccelli", "Matias Macelli") ~ "Matias Maccelli",
    player %in% c("Maxwell Crozier") ~ "Max Crozier",
    player %in% c("Michael Teply") ~ "Michal Teply",
    player %in% c("Michael Koster") ~ "Mike Koster",
    player %in% c("Mortiz Seider") ~ "Moritz Seider",
    player %in% c("Nicholas Abruzzese") ~ "Nick Abruzzese",
    player %in% c("Nicholas Robertson") ~ "Nick Robertson",
    player %in% c("Oleg Zaitsev") ~ "Oleg Zaytsev",
    player %in% c("Phil Tomasino", "Phillip Tomasino") ~ "Philip Tomasino",
    player %in% c("Ronald Attard", "Ron Attard") ~ "Ronnie Attard",
    player %in% c("Semyon Chystyakov") ~ "Semyon Chistyakov",
    player %in% c("William Constantinou") ~ "Billy Constantinou",
    player %in% c("Will Francis") ~ "William Francis",
    player %in% c("Yaroslav Likhachev") ~ "Yaroslav Likhachyov",
    grepl("Afanas", player) & year == 2019 ~ "Yegor Afanasyev",
    player %in% c("Zachary Jones") ~ "Zac Jones",
    
    ## 2018 Draft ##
    player %in% c("Alexander Steeves") ~ "Alex Steeves",
    grepl("Groulx", player) & year == 2018 ~ "Benoit-Olivier Groulx",
    player %in% c("Cam Hillis") ~ "Cameron Hillis",
    player %in% c("Danila Galeniuk") ~ "Danila Galenyuk",
    player %in% c("Danil Zhuravlyov", "Daniil Zhuravlyov") ~ "Danila Zhuravlyov",
    player %in% c("Dmitry Zavgorodniy") ~ "Dmitri Zavgorodny",
    player %in% c("Isac Lunderstrom") ~ "Isac Lundestrom",
    player %in% c("Jackson Perbix") ~ "Jack Perbix",
    player %in% c("Jake Pivonka") ~ "Jacob Pivonka",
    player %in% c("Jacob Ragnarsson", "Jakob Ragnarson", "Jacob Ragnarson") ~ "Jakob Ragnarsson",
    player %in% c("Jet Woo") ~ "Jett Woo",
    player %in% c("Jacob Ingram") ~ "Jacob Ingham",
    player %in% c("Joseph Veleno") ~ "Joe Veleno",
    player %in% c("Jack St. Ivany", "Jack St Ivany", "John St Ivany") ~ "John St. Ivany",
    player %in% c("Jon Gruden", "Jonny Gruden", "Johnny Gruden", "Johnny Grudin") ~ "Jonathan Gruden",
    grepl("Tychonick", player) & year == 2018 ~ "Jonathan Tychonick",
    player %in% c("Lukas Gustavsson") & year %in% c(2017, 2018) ~ "Lucas Gustavsson",
    player %in% c("Kevin Madnolese") ~ "Kevin Mandolese",
    player %in% c("Kody Clarke") ~ "Kody Clark",
    player %in% c("Marcus Westfelt") ~ "Marcus Westfalt",
    player %in% c("Emilio Pettersen", "Mathias Pettersen", "M.E. Pettersen", "ME Pettersen") ~ "Mathias Emilio Pettersen",
    player %in% c("Mike Callahan") ~ "Michael Callahan",
    player %in% c("Nils Lundqvist") ~ "Nils Lundkvist",
    player %in% c("Oscar Back") ~ "Oskar Back",
    player %in% c("Quintin Hughes", "Quinton Hughes") ~ "Quinn Hughes",
    player %in% c("Ramus Kupari", "Rasmus Kapuri") ~ "Rasmus Kupari",
    player %in% c("Santeri Salmala") ~ "Santeri Salmela",
    player %in% c("Slava Demin") ~ "Stanislav Demin",
    player %in% c("Ty Emberton", "Tyler Emberson") ~ "Ty Emberson",
    player %in% c("Will Bitten") ~ "William Bitten",
    
    ## 2017 Draft ##
    player %in% c("Aleksei Heponiemi") ~ "Aleksi Heponiemi",
    player %in% c("Artyom Myulin") ~ "Artyom Minulin",
    player %in% c("Benjamin Mirageas") ~ "Ben Mirageas",
    player %in% c("Callan Foote") ~ "Cal Foote",
    player %in% c("Casey Mittlestadt") ~ "Casey Mittelstadt",
    player %in% c("Gabe Vilardi") ~ "Gabriel Vilardi",
    player %in% c("Igor Shvyrev") ~ "Igor Shvyryov",
    player %in% c("Ivan Chechovich") ~ "Ivan Chekhovich",
    player %in% c("Jonathan Dugan") ~ "Jack Dugan",
    player %in% c("Jake Leschyschyn") ~ "Jake Leschyshyn",
    player %in% c("Jaret A-Dolan") ~ "Jaret Anderson-Dolan",
    player %in% c("Jarrett Tyszka", "Jarret Tyzska") ~ "Jarret Tyszka",
    player %in% c("Jack Adams") ~ "John Adams",
    player %in% c("Jonathan Kovacevic", "Johnathan Kovacevic", "John Kovacevic") ~ "Johnny Kovacevic",
    player %in% c("Joshua Norris") ~ "Josh Norris",
    grepl("Eriksson", player) & grepl("Ek", player) & year == 2017 ~ "Olle Eriksson-Ek",
    player %in% c("Joshua Ess") ~ "Josh Ess",
    player %in% c("Jusso Valimaki") ~ "Juuso Valimaki",
    player %in% c("Kirill Maksimov") ~ "Kirill Maximov",
    grepl("Marthinsen", player) & year == 2017 ~ "Kristian Roykas-Marthinsen",
    player %in% c("Lukas Elvenes") ~ "Lucas Elvenes",
    player %in% c("Mackenzie Entwhistle") ~ "MacKenzie Entwistle",
    grepl("Matthew Phil", player) & year == 2017 ~ "Matthew Philip",
    player %in% c("Maksim Sushko") ~ "Maxim Sushko",
    player %in% c("Maksim Zhukov") ~ "Maxim Zhukov",
    player %in% c("Maxwell Gildon") ~ "Max Gildon",
    player %in% c("Michael Anderson") ~ "Mikey Anderson",
    player %in% c("Nic Hague", "Nick Hague", "Nicholas Hague") ~ "Nicolas Hague",
    player %in% c("Nicklaus Perbix", "Nicholas Perbix") ~ "Nick Perbix",
    player %in% c("Noel Hoefenmeyer") ~ "Noel Hoefenmayer",
    player %in% c("P-Olivier Joseph") ~ "Pierre-Olivier Joseph",
    player %in% c("Ryan Poeling") ~ "Ryan Poehling",
    grepl("Chmelevski", player) & year == 2017 ~ "Sasha Chmelevski",
    player %in% c("Thomas Miller") & year == 2017 ~ "Tommy Miller",
    player %in% c("Trenton Bourque") ~ "Trent Bourque",
    grepl("Luukkonen", player) & year == 2017 ~ "Ukko-Pekka Luukkonen",
    player %in% c("U-P Luukkonen", "U.P. Luukkonen", "Ukko Pekka Luukkonen") ~ "Ukko-Pekka Luukkonen",
    player %in% c("Urho Vaakainainen", "Urho Vaakainen") ~ "Urho Vaakanainen",
    player %in% c("William Reilly") ~ "Will Reilly",
    player %in% c("Zach Gallant") ~ "Zachary Gallant",
    player %in% c("Zach Solow") ~ "Zachary Solow",
    
    ## 2016 Draft ##
    player %in% c("Alexander Debrincat", "Alexander DeBrincat") ~ "Alex DeBrincat",
    player %in% c("Alexander Nylander") ~ "Alex Nylander",
    player %in% c("Benjamin Finkelstein") ~ "Ben Finkelstein",
    player %in% c("Cam Clarke") ~ "Cameron Clarke",
    grepl("Dodero", player) & year == 2016 ~ "Christopher Dodero",
    player %in% c("Cam Morrison") ~ "Cameron Morrison",
    player %in% c("Charles McAvoy", "Charles Mcavoy") ~ "Charlie McAvoy",
    player %in% c("Dylan Gambrel") ~ "Dylan Gambrell",
    player %in% c("German Rubstov") ~ "German Rubtsov",
    player %in% c("James Greenway") ~ "J.D. Greenway",
    grepl("Truchon", player) & grepl("Viel", player) & year == 2016 ~ "Jeffrey Viel",
    player %in% c("Jordy Stallard") ~ "Jordan Stallard",
    player %in% c("Joseph Anderson") & year == 2016 ~ "Joey Anderson",
    player %in% c("Joshua Mahura") ~ "Josh Mahura",
    player %in% c("Kiefer Bellows") ~ "Kieffer Bellows",
    grepl("Matthew Phil", player) & year == 2016 ~ "Matthew Phillips",
    player %in% c("Max Lajoie", "Maxim Lajoie") ~ "Maxime Lajoie",
    player %in% c("Mikey Eyssimont", "Mikey Essiymont") ~ "Michael Eyssimont",
    player %in% c("Mike McLeod", "Mikey McLeod", "Michael MacLeod", "Mike MacLeod") ~ "Michael McLeod",
    player %in% c("Mikhail Sergachyov") ~ "Mikhail Sergachev",
    player %in% c("Nathan Clurman") ~ "Nate Clurman",
    player %in% c("Nicolas Caamano", "Nicholas Camano", "Nick Camano", "Nicholas Caamano") ~ "Nick Caamano",
    player %in% c("Nikita O Popugaev", "Nikita O. Popugaev") & year == 2016 ~ "Nikita Popugaev",
    player %in% c("Timothy Gettinger") ~ "Tim Gettinger",
    player %in% c("William Lockwood") ~ "Will Lockwood",
    player %in% c("Zachary Sawchenko") ~ "Zach Sawchenko",
    player %in% c("Zachary Walker") ~ "Zach Walker",
    
    ## 2015 Draft ##
    player %in% c("Alexander Georgiyev", "Alexander Georgiev", "Alexandar Georgiyev") ~ "Alexandar Georgiev",
    grepl("Dergachev", player) & year == 2015 ~ "Alexander Dergachyov",
    grepl("Misha", player) & grepl("Song", player) ~ "AnDong Song",
    player %in% c("Christopher Wilkie") ~ "Chris Wilkie",
    player %in% c("Colon White") ~ "Colin White",
    player %in% c("Dan Vladar", "Daniel Vlader") ~ "Daniel Vladar",
    grepl("Greer", player) & year == 2015 ~ "A.J. Greer",
    player %in% c("Denis Guryanov", "Dennis Guryanov", "Dennis Gurianov") ~ "Denis Gurianov",
    player %in% c("Grant Gabrielle") ~ "Grant Gabriele",
    grepl("Roslovic", player) & year == 2015 ~ "Jack Roslovic",
    player %in% c("J. Forsbacka Karlsson", "J. Forsbacka-Karlsson", "Jakob F-Karlsson") ~ "Jakob Forsbacka-Karlsson",
    grepl("Eriksson", player) & grepl("Ek", player) & year == 2015 ~ "Joel Eriksson-Ek",
    player %in% c("Joseph Masonius", "Joey Masonius") ~ "Joe Masonius",
    player %in% c("Joel Daccord", "Joe Daccord", "Joseph Daccord") ~ "Joey Daccord",
    player %in% c("Kristian Oldham", "Christian Oldham") ~ "Kris Oldham",
    player %in% c("Mitchell Marner") ~ "Mitch Marner",
    grepl("vande Sompel", player) & year == 2015 ~ "Mitchell Vande Sompel",
    player %in% c("M. Vande Sompel", "Mitch Vande Sompel", "Mitchell V. Sompel") ~ "Mitchell Vande Sompel",
    player %in% c("Nicholas Boka", "Nicolas Boka") ~ "Nick Boka",
    player %in% c("Nicholas Merkley", "Nicolas Merkley") ~ "Nick Merkley",
    player %in% c("Nicklaus Poehling", "Nicholas Poehling", "Niklaus Poehling") ~ "Nick Poehling",
    player %in% c("Sergey Zborovskiy", "Sergey Zborovsky", "Sergei Zborovskiy") ~ "Sergei Zborovsky",
    player %in% c("Tommy Novak") ~ "Thomas Novak",
    grepl("Ahrens", player) & year == 2015  ~ "Vaughan Ahrens",
    player %in% c("Vladimir Tkachev") ~ "Vladimir Tkachyov",
    player %in% c("William Borgen") ~ "Will Borgen",
    player %in% c("Iakov Trenin") ~ "Yakov Trenin",
    player %in% c("Zachary Werenski") ~ "Zach Werenski",
    player %in% c("Zachary Senyshyn") ~ "Zach Senyshyn",
    player %in% c("Zach Zborosky", "Zac Zborosky", "Zak Zborosky") ~ "Zachary Zborosky",
    player %in% c("Ziyat Paygin") ~ "Ziyat Paigin",
    
    ## RUSSIAN NAME STANDARDIZATION ##
    grepl("Artem ", player) ~ str_replace(player, "Artem ", "Artyom "),
    grepl("Aliaksei ", player) ~ str_replace(player, "Aliaksei ", "Alexei "),
    grepl("Alexey ", player) ~ str_replace(player, "Alexey ", "Alexei "),
    grepl("Anatoly ", player) ~ str_replace(player, "Anatoly ", "Anatoli "),
    grepl("Anatoliy ", player) ~ str_replace(player, "Anatoliy ", "Anatoli "),
    grepl("Arseny ", player) ~ str_replace(player, "Arseny ", "Arseni "),
    grepl("Arseniy ", player) ~ str_replace(player, "Arseniy ", "Arseni "),
    grepl("Dmitry ", player) ~ str_replace(player, "Dmitry ", "Dmitri "),
    grepl("Dmitriy ", player) ~ str_replace(player, "Dmitriy ", "Dmitri "),
    grepl("Evgeny ", player) ~ str_replace(player, "Evgeny ", "Evgeni "),
    grepl("Evgenii ", player) ~ str_replace(player, "Evgenii ", "Evgeni "),
    grepl("Evgeniy ", player) ~ str_replace(player, "Evgeniy ", "Evgeni "),
    grepl("Yevgeni ", player) ~ str_replace(player, "Yevgeni ", "Evgeni "),
    grepl("Matvey ", player) ~ str_replace(player, "Matvey ", "Matvei "),
    grepl("Nikolay ", player) ~ str_replace(player, "Nikolay ", "Nikolai "),
    grepl("Sergey ", player) ~ str_replace(player, "Sergey ", "Sergei "),
    grepl("Sergeiy ", player) ~ str_replace(player, "Sergeiy ", "Sergei "),
    grepl("Timofey ", player) ~ str_replace(player, "Timofey ", "Timofei "),
    grepl("Timofeiy ", player) ~ str_replace(player, "Timofeiy ", "Timofei "),
    grepl("Vasily ", player) ~ str_replace(player, "Vasily ", "Vasili "),
    grepl("Vitalii ", player) ~ str_replace(player, "Vitalii ", "Vitali "),
    grepl("Vitaly ", player) ~ str_replace(player, "Vitaly ", "Vitali "),
    grepl("Vitaliy ", player) ~ str_replace(player, "Vitaliy ", "Vitali "),
    grepl("Iaroslav ", player) ~ str_replace(player, "Iaroslav ", "Yaroslav "),
    grepl("Egor ", player) ~ str_replace(player, "Egor ", "Yegor "),
    
    ## HYPHEN STANDARDIZATION ##
    grepl("Barre Boulet", player) ~ str_replace(player, "Barre Boulet", "Barre-Boulet"),
    grepl("Bolling Vaaler", player) ~ str_replace(player, "Bolling Vaaler", "Bolling-Vaaler"),
    grepl("Cote Cazenave", player) ~ str_replace(player, "Cote Cazenave", "Cote-Cazenave"),
    grepl("Dower Nilsson", player) ~ str_replace(player, "Dower Nilsson", "Dower-Nilsson"),
    grepl("Ekestahl Jonsson", player) ~ str_replace(player, "Ekestahl Jonsson", "Ekestahl-Jonsson"),
    grepl("Forsbacka Karlsson", player) ~ str_replace(player, "Forsbacka Karlsson", "Forsbacka-Karlsson"),
    grepl("Gatz Nielsen", player) ~ str_replace(player, "Gatz Nielsen", "Gatz-Nielsen"),
    grepl("Gil-Shane", player) ~ str_replace(player, "Gil-Shane", "Gill-Shane"),
    grepl("Haman Aktell", player) ~ str_replace(player, "Haman Aktell", "Haman-Aktell"),
    grepl("Johansen Halmrast", player) ~ str_replace(player, "Johansen Halmrast", "Johansen-Halmrast"),
    grepl("Jonsson Fjallby", player) ~ str_replace(player, "Jonsson Fjallby", "Jonsson-Fjallby"),
    grepl("Jon-rand", player) ~ str_replace(player, "Jon-rand", "Jon-Rand"),
    grepl("Kannok Leipert", player) ~ str_replace(player, "Kannok Leipert", "Kannok-Leipert"),
    grepl("Krag Christensen", player) ~ str_replace(player, "Krag Christensen", "Krag-Christensen"),
    grepl("Limpar Lantz", player) ~ str_replace(player, "Limpar Lantz", "Limpar-Lantz"),
    grepl("Martinsen Lilleberg", player) ~ str_replace(player, "Martinsen Lilleberg", "Martinsen-Lilleberg"),
    grepl("Muzito Bagenda", player) ~ str_replace(player, "Muzito Bagenda", "Muzito-Bagenda"),
    grepl("Ratkovic Berndtsson", player) ~ str_replace(player, "Ratkovic Berndtsson", "Ratkovic-Berndtsson"),
    grepl("Roykas Marthinsen", player) ~ str_replace(player, "Roykas Marthinsen", "Roykas-Marthinsen"),
    grepl("Sandin Pellikka", player) ~ str_replace(player, "Sandin Pellikka", "Sandin-Pellikka"),
    grepl("Schmidt Svejstrup", player) ~ str_replace(player, "Schmidt Svejstrup", "Schmidt-Svejstrup"),
    grepl("Slettebo Haughom", player) ~ str_replace(player, "Slettebo Haughom", "Slettebo-Haughom"),
    grepl("Walli Walterholm", player) ~ str_replace(player, "Walli Walterholm", "Walli-Walterholm"),
    grepl("Worge Kreu", player) ~ str_replace(player, "Worge Kreu", "Worge-Kreu"),
    grepl("- ", player) ~ str_replace(player, "- ", "-"),
    
    ## CAPITALIZATION AND PUNCTUATION FIXES ##
    grepl("Charles-alexis", player) ~ str_replace(player, "alexis", "Alexis"),
    grepl("Deboer", player) ~ str_replace(player, "Deboer", "DeBoer"),
    grepl("Debrincat", player) ~ str_replace(player, "Debrincat", "DeBrincat"),
    grepl("Debrusk", player) ~ str_replace(player, "Debrusk", "DeBrusk"),
    grepl("Degrazia", player) ~ str_replace(player, "Degrazia", "DeGrazia"),
    grepl("Divincentiis", player) ~ str_replace(player, "Divincentiis", "DiVincentiis"),
    grepl("Dipietro", player) ~ str_replace(player, "Dipietro", "DiPietro"),
    grepl("K'andre", player) ~ str_replace(player, "K'andre", "K'Andre"),
    grepl("Lachance", player) ~ str_replace(player, "Lachance", "LaChance"),
    grepl("Lacombe", player) ~ str_replace(player, "Lacombe", "LaCombe"),
    grepl("Lafontaine", player) ~ str_replace(player, "Lafontaine", "LaFontaine"),
    grepl("Leguerrier", player) ~ str_replace(player, "Leguerrier", "LeGuerrier"),
    grepl("L'h", player) ~ str_replace(player, "L'h", "L'H"),
    grepl("Macarthur", player) ~ str_replace(player, "Macarthur", "MacArthur"),
    grepl("Macaulay", player) ~ str_replace(player, "Macaulay", "MacAulay"),
    grepl("Macdonald", player) ~ str_replace(player, "Macdonald", "MacDonald"),
    grepl("Macdougall", player) ~ str_replace(player, "Macdougall", "MacDougall"),
    grepl("Macinnes", player) ~ str_replace(player, "Macinnes", "MacInnes"),
    grepl("Mackay", player) ~ str_replace(player, "Mackay", "MacKay"),
    grepl("Mackenzie", player) ~ str_replace(player, "Mackenzie", "MacKenzie"),
    grepl("Maclean", player) ~ str_replace(player, "Maclean", "MacLean"),
    grepl("Macnab", player) ~ str_replace(player, "Macnab", "MacNab"),
    grepl("Macpherson", player) ~ str_replace(player, "Macpherson", "MacPherson"),
    grepl("Mcbain", player) ~ str_replace(player, "Mcbain", "McBain"),
    grepl("Mcbride", player) ~ str_replace(player, "Mcbride", "McBride"),
    grepl("Mccallum", player) ~ str_replace(player, "Mccallum", "McCallum"),
    grepl("Mccart", player) ~ str_replace(player, "Mccart", "McCart"),
    grepl("Mccleary", player) ~ str_replace(player, "Mccleary", "McCleary"),
    grepl("Mcclennon", player) ~ str_replace(player, "Mcclennon", "McClennon"),
    grepl("Mcconnell", player) ~ str_replace(player, "Mcconnell", "McConnell"),
    grepl("Mccool", player) ~ str_replace(player, "Mccool", "McCool"),
    grepl("Mccormick", player) ~ str_replace(player, "Mccormick", "McCormick"),
    grepl("Mccourt", player) ~ str_replace(player, "Mccourt", "McCourt"),
    grepl("Mccue", player) ~ str_replace(player, "Mccue", "McCue"),
    grepl("Mcdavid", player) ~ str_replace(player, "Mcdavid", "McDavid"),
    grepl("Mcdermott", player) ~ str_replace(player, "Mcdermott", "McDermott"),
    grepl("Mcdon", player) ~ str_replace(player, "Mcdon", "McDon"),
    grepl("Mcelh", player) ~ str_replace(player, "Mcelh", "McElh"),
    grepl("Mcewan", player) ~ str_replace(player, "Mcewan", "McEwan"),
    grepl("Mcfadden", player) ~ str_replace(player, "Mcfadden", "McFadden"),
    grepl("Mcfalls", player) ~ str_replace(player, "Mcfalls", "McFalls"),
    grepl("Mcfaul", player) ~ str_replace(player, "Mcfaul", "McFaul"),
    grepl("Mcgauley", player) ~ str_replace(player, "Mcgauley", "McGauley"),
    grepl("Mcgovern", player) ~ str_replace(player, "Mcgovern", "McGovern"),
    grepl("Mcgrath", player) ~ str_replace(player, "Mcgrath", "McGrath"),
    grepl("Mcgregor", player) ~ str_replace(player, "Mcgregor", "McGregor"),
    grepl("Mcgroarty", player) ~ str_replace(player, "Mcgroarty", "McGroarty"),
    grepl("Mcguire", player) ~ str_replace(player, "Mcguire", "McGuire"),
    grepl("Mchugh", player) ~ str_replace(player, "Mchugh", "McHugh"),
    grepl("Mcindoe", player) ~ str_replace(player, "Mcindoe", "McIndoe"),
    grepl("Mcinnis", player) ~ str_replace(player, "Mcinnis", "McInnis"),
    grepl("Mcintosh", player) ~ str_replace(player, "Mcintosh", "McIntosh"),
    grepl("Mcisaac", player) ~ str_replace(player, "Mcisaac", "McIsaac"),
    grepl("Mckenna", player) ~ str_replace(player, "Mckenna", "McKenna"),
    grepl("Mckenzie", player) ~ str_replace(player, "Mckenzie", "McKenzie"),
    grepl("Mckown", player) ~ str_replace(player, "Mckown", "McKown"),
    grepl("Mclaughlin", player) ~ str_replace(player, "Mclaughlin", "McLaughlin"),
    grepl("Mclean", player) ~ str_replace(player, "Mclean", "McLean"),
    grepl("Mcleod", player) ~ str_replace(player, "Mcleod", "McLeod"),
    grepl("Mcmanus", player) ~ str_replace(player, "Mcmanus", "McManus"),
    grepl("Mcmichael", player) ~ str_replace(player, "Mcmichael", "McMichael"),
    grepl("Mcnaughton", player) ~ str_replace(player, "Mcnaughton", "McNaughton"),
    grepl("Mcneely", player) ~ str_replace(player, "Mcneely", "McNeely"),
    grepl("Mcniven", player) ~ str_replace(player, "Mcniven", "McNiven"),
    grepl("Mcphee", player) ~ str_replace(player, "Mcphee", "McPhee"),
    grepl("Mcshane", player) ~ str_replace(player, "Mcshane", "McShane"),
    grepl("Mctavish", player) ~ str_replace(player, "Mctavish", "McTavish"),
    grepl("St ", player) ~ str_replace(player, "St ", "St. "),
    grepl("van Pott", player) ~ str_replace(player, "van Pott", "Van Pott"),
    
    ## COMMON NAME FIXES ##
    grepl("Bobylev", player) ~ str_replace(player, "Bobylev", "Bobylyov"),
    grepl("Christopolous", player) ~ str_replace(player, "Christopolous", "Christopoulos"),
    grepl("Jasnsson", player) ~ str_replace(player, "Jasnsson", "Jansson"),
    grepl("Matt ", player) ~ str_replace(player, "Matt ", "Matthew "),
    grepl("Nikolaev", player) ~ str_replace(player, "Nikolaev", "Nikolayev"),
    grepl("Pettrovsky", player) ~ str_replace(player, "Pettrovsky", "Petrovsky"),
    grepl("Popugayev", player) ~ "Popugaev",
    grepl("Simontaval", player) ~ str_replace(player, "Simontaval", "Simontaival"),
    grepl("Sychev", player) ~ str_replace(player, "Sychev", "Sychyov"),
    
    TRUE ~ player
  )
  
  return(player)
  
}